platform :ios, '14.0'

target 'Hoodie' do
  use_frameworks!

  
  pod 'Firebase'
  pod 'FirebaseDatabase'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'

  # Alerts and popup
  pod 'FCAlertView'
  pod 'SwiftMessages'
  pod 'PopupDialog'

  # Google Signin
  pod 'GoogleSignIn'

  # Facebook Signin
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
end